# Generated by Django 4.0.3 on 2022-03-23 05:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0003_alter_product_onsale_alter_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('e0feb6b4-7d39-4d1d-bd5c-1f47e95e4728')),
        ),
        migrations.CreateModel(
            name='Sn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn_name', models.CharField(max_length=30, unique=True)),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mart.ca')),
            ],
        ),
    ]
