# Generated by Django 4.0.3 on 2022-03-23 06:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0004_ca_alter_product_sku_sn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sn',
            old_name='ca',
            new_name='ca_parent',
        ),
        migrations.AddField(
            model_name='ca',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sn',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('5da6a406-d01d-4eff-bc3a-4ce519e0f085')),
        ),
    ]
