# Generated by Django 4.0.3 on 2022-03-23 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0005_rename_ca_sn_ca_parent_ca_status_sn_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sn',
            old_name='ca_parent',
            new_name='ca_id',
        ),
        migrations.RemoveField(
            model_name='ca',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sn',
            name='status',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('b4edb8f0-aaef-45a1-a390-4e8aaf36159e')),
        ),
    ]
