# Generated by Django 4.0.3 on 2022-03-24 12:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0006_rename_ca_parent_sn_ca_id_remove_ca_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sn',
            name='ca_id',
        ),
        migrations.AddField(
            model_name='sn',
            name='sub_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sn_id', to='mart.ca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('6bd92531-7fdd-4b99-b6b3-3e7f26cf8cfc')),
        ),
    ]
