# Generated by Django 4.0.3 on 2022-03-25 05:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0007_remove_sn_ca_id_sn_sub_id_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sn',
            name='sub_id',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='types',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='types',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('08d0db11-6726-46d4-b378-c3574d58d746')),
        ),
        migrations.DeleteModel(
            name='Ca',
        ),
        migrations.DeleteModel(
            name='Sn',
        ),
    ]
