# Generated by Django 4.0.3 on 2022-03-25 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0009_rename_cat_category_genre_rename_name_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('a3e06687-5ee4-4cfb-8f7a-73a9830e08f6')),
        ),
    ]
