# Generated by Django 4.0.3 on 2022-03-25 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0010_alter_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_url', models.ImageField(blank=True, null=True, upload_to='mudi')),
            ],
        ),
        migrations.RenameModel(
            old_name='ColorsOptions',
            new_name='ColorsOption',
        ),
        migrations.RenameModel(
            old_name='SizeOptions',
            new_name='SizesOption',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='images_url',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('bc34eaf7-2e00-4c7e-b4c6-daca38ac1a15')),
        ),
        migrations.AddField(
            model_name='variants',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mart.imagesoption'),
        ),
    ]
