# Generated by Django 4.0.3 on 2022-03-25 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0015_variant_imagesoption_product_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesoption',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.AddField(
            model_name='variant',
            name='images_url',
            field=models.ImageField(blank=True, null=True, upload_to='mudi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('50a65643-09e2-44de-bdb6-769d398d07d6')),
        ),
        migrations.DeleteModel(
            name='Additional',
        ),
        migrations.DeleteModel(
            name='ImagesOption',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
