# Generated by Django 4.0.3 on 2022-03-25 09:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0016_remove_imagesoption_product_remove_inventory_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorsoption',
            name='color_name',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('3d86f775-149c-4ae0-b619-a8bb5f7b90ec')),
        ),
        migrations.AlterField(
            model_name='sizesoption',
            name='size_name',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
