# Generated by Django 4.0.3 on 2022-03-25 09:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0017_alter_colorsoption_color_name_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('58a9c2f2-ec48-496c-8fc5-e82ae916b8f1')),
        ),
    ]
