# Generated by Django 4.0.3 on 2022-03-25 12:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0018_alter_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='mudi')),
            ],
        ),
        migrations.RemoveField(
            model_name='variant',
            name='images_url',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('52b58e6b-3f28-4cef-8c77-581fdc61330b')),
        ),
        migrations.AddField(
            model_name='variant',
            name='image_urls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mart.futuredimages'),
        ),
    ]
