# Generated by Django 4.0.3 on 2022-03-25 12:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0019_futuredimages_remove_variant_images_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='image_urls',
        ),
        migrations.AddField(
            model_name='futuredimages',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mart.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('f8dccb28-30d5-4f9d-b8a6-f1383dc8669e')),
        ),
    ]
