# Generated by Django 4.0.3 on 2022-03-27 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0020_remove_variant_image_urls_futuredimages_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('cdfcdb85-4e0e-4460-b38f-4c5896a57986')),
        ),
    ]
